services:
  - type: web
    name: assesslyplatform
    env: node
    plan: free
    region: frankfurt
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 22
      - key: PORT
        value: 8080
      - key: VITE_API_BASE_URL
        value: https://assesslyplatform.onrender.com/api
      - key: VITE_STRIPE_PUBLIC_KEY
        sync: false

    routes:
      # ✅ Rewrites for SPA navigation
      - type: rewrite
        source: /*
        destination: /index.html
