# ===========================
# Assessly Platform Netlify Configuration
# ===========================

[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  VITE_ENV = "production"

# =======================================
# React SPA Routing Fix (White Screen Fix)
# =======================================
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# =======================================
# API Requests Redirect to Render Backend
# =======================================
[[redirects]]
  from = "/api/*"
  to = "https://assesslyplatform.onrender.com/api/:splat"
  status = 200
  force = true

# =======================================
# Security + Performance Headers
# =======================================
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Cache-Control = "public, max-age=31536000, immutable"
